apiVersion: v1
kind: Secret
metadata:
  name: mutator-pems
type: Opaque
data:
  key.pem:  {{ .Values.crypt.mutator.key  | b64enc | nindent 4 }}
  cert.pem: {{ .Values.crypt.mutator.cert | b64enc | nindent 4 }}
