apiVersion: v1
kind: Service
metadata:
  name: mutator
  labels:
    app: kubetechno-mutator
spec:
  selector:
    app: kubetechno-mutator
  ports:
  - port: 443
    targetPort: 443
  type: ClusterIP # does not need to be reachable outside the cluster
