img:
  pullPolicy: Always
  interceptor: localhost:5000/kubetechno/interceptor:tmp
  mutator: localhost:5000/kubetechno/mutator:tmp
  consulClient: localhost:5000/kubetechno/consul-client:tmp
settings:
  lowerPortBound: '9000' # inclusive bound
  upperPortBound: '10000' # exclusive bound
  disallowedPorts: '9002,9004'
crypt:
  mutator:
    cABundle: ''
    key: ''
    cert: ''
  interceptor:
    cABundle: ''
    key: ''
    cert: ''