apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: kubetechno-interceptor
  labels:
    app: kubetechno-interceptor
webhooks:
  - name: bind-hook.interceptor.kubetechno
    admissionReviewVersions:
      - 'v1'
    clientConfig:
      service:
        name: interceptor
        namespace: kubetechno
        path: "/bind-hook"
        port: 443
      caBundle: {{ .Values.crypt.interceptor.cABundle }}
    rules:
      - operations:
        - "CREATE"
        apiGroups:
        - ""
        apiVersions:
        - "v1"
        resources:
        - "pods/binding"
    namespaceSelector:
      matchLabels:
        kubetechno: user
    failurePolicy: Fail
    sideEffects: NoneOnDryRun
