apiVersion: v1
kind: Secret
metadata:
  name: interceptor-pems
type: Opaque
data:
  key.pem:  {{ .Values.crypt.interceptor.key  | b64enc | nindent 4 }}
  cert.pem: {{ .Values.crypt.interceptor.cert | b64enc | nindent 4 }}
