apiVersion: v1
kind: Service
metadata:
  name: interceptor
  labels:
    app: kubetechno-interceptor
spec:
  selector:
    app: kubetechno-interceptor
  ports:
  - port: 443
    targetPort: 443
  type: ClusterIP # does not need to be reachable outside the cluster
